# Copyright 2021 the GLanguage authors. All rights reserved. MIT license.

[workspace]
members = [
	"gl-cli",
	"gl-core",
	"gl-fmt",
	"gl-runtime",
	"gl-std",
]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
lto = true

